### ISSUE TITLE
Can not create logfile when using simulator

### ISSUE THREAD

**Issue by johandb** [rhymelph/r_logger#1]
When using simulator on Android I have error message, see below

E/flutter (27030): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Cannot create file, path = 'pyrolog.log' (OS Error: Read-only file system, errno = 30)
E/flutter (27030): #0      _File.create.<anonymous closure> (dart:io/file_impl.dart:255:9)
E/flutter (27030): <asynchronous suspension>
E/flutter (27030): #1      _RFileWriter.writeLog (package:r_logger/r_logger.dart:161:7)
E/flutter (27030): <asynchronous suspension>

**Comment by johandb** [comment]
i added permissions and is ok now
